- name: Get the binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ prometheus_node_exporter_version }}/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_architecture }}.tar.gz" # noqa: yaml[line-length]
    dest: "/var/cache/"
    checksum: "sha256:{{ prometheus_node_exporter_checksum }}"
    owner: root
    group: root
    mode: "0644"

- name: Unarchive the binary
  ansible.builtin.unarchive:
    src: "/var/cache/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_architecture }}.tar.gz"
    dest: "/var/cache/"
    remote_src: true
    owner: root
    group: root
    mode: "0755"

- name: Copy the binary
  ansible.builtin.copy:
    src: "/var/cache/node_exporter-{{ prometheus_node_exporter_version }}.linux-{{ prometheus_node_exporter_architecture }}/node_exporter"
    dest: "/usr/bin/prometheus-node-exporter"
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  notify:
    - Restart node exporter

- name: Add the service
  ansible.builtin.template:
    src: prometheus-node-exporter.service.j2
    dest: "/etc/systemd/system/prometheus-node-exporter.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Restart node exporter

- name: Start the node exporter
  ansible.builtin.systemd:
    name: prometheus-node-exporter
    enabled: true
    daemon_reload: true
    state: started
